<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bill Pay</name>
   <tag></tag>
   <elementGuidId>15fbda24-a7c1-47f4-b548-8e7aa33d1dd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftPanel']/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>43704b8a-bdde-4566-92ec-b48deec32fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/parabank/billpay.htm</value>
      <webElementGuid>b7e3a678-4d78-4687-a4b5-3f7e44dab56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bill Pay</value>
      <webElementGuid>c6a7ea15-d26a-450f-b4e9-b77389f7d539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftPanel&quot;)/ul[1]/li[4]/a[1]</value>
      <webElementGuid>897321ed-9c84-48da-a3b0-482ef710ced1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftPanel']/ul/li[4]/a</value>
      <webElementGuid>1a206252-172f-4041-bfa8-cdb65d2db60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bill Pay')]</value>
      <webElementGuid>9770b545-9637-4b6f-92f8-aae7d08ec317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer Funds'])[1]/following::a[1]</value>
      <webElementGuid>bb7951b7-a098-4fba-92d8-dbc23e417a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounts Overview'])[1]/following::a[2]</value>
      <webElementGuid>7572b98d-39bb-409c-a347-61fac1b6f921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find Transactions'])[1]/preceding::a[1]</value>
      <webElementGuid>f0d9b8b1-d040-4a51-a8e5-363066049623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Contact Info'])[1]/preceding::a[2]</value>
      <webElementGuid>2f37e117-2f5a-46b4-bdc7-f63fc659386b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bill Pay']/parent::*</value>
      <webElementGuid>ab0d895f-6a9d-408b-8cde-e6f121341d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/parabank/billpay.htm')]</value>
      <webElementGuid>36a7880d-b8e6-4063-9314-d0441e47cbbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[4]/a</value>
      <webElementGuid>d3b4653d-4dbd-4db1-9ca0-dd6c6f610da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/parabank/billpay.htm' and (text() = 'Bill Pay' or . = 'Bill Pay')]</value>
      <webElementGuid>f7d258fb-afa1-4d0d-8d7d-03f58dab295e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
