<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input Phone</name>
   <tag></tag>
   <elementGuidId>49b29117-d884-4e4e-bb62-b6c3ca8f2e10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='7ee92df8-a0be-4c85-b861-8a333bc6c3fd']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'payee.phoneNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#7ee92df8-a0be-4c85-b861-8a333bc6c3fd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ebab75a-8469-48b6-b9e7-eebcfff9dcd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7ee92df8-a0be-4c85-b861-8a333bc6c3fd</value>
      <webElementGuid>2b877ce9-7d04-4e87-90fd-84aa637e78aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input phone-number-7ee92df8-a0be-4c85-b861-8a333bc6c3fd ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>e9a0dd02-730b-4bba-b87d-c3e0e8158814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>payee.phoneNumber</value>
      <webElementGuid>5d149680-4d3b-4d0d-8de8-9609d40f4de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payee.phoneNumber</value>
      <webElementGuid>6b25850b-910e-41cc-8a33-6252a1689902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7ee92df8-a0be-4c85-b861-8a333bc6c3fd&quot;)</value>
      <webElementGuid>b901637d-366d-468a-ad25-f2b37ef84af0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='7ee92df8-a0be-4c85-b861-8a333bc6c3fd']</value>
      <webElementGuid>39cf1210-9a57-4efc-af55-e14b18f60dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>385f44b8-c5b2-4ad3-af93-eba557a7e6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>3b68ad9f-fe9f-4d20-b9bf-7d8fd4ab7b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '7ee92df8-a0be-4c85-b861-8a333bc6c3fd' and @name = 'payee.phoneNumber']</value>
      <webElementGuid>8aff29aa-19a9-4246-ac5b-3a99050daa13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
