<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select from account</name>
   <tag></tag>
   <elementGuidId>58ff7303-aeb6-4577-b21a-848edace0d46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toAccountId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='toAccountId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>07418442-0964-41ff-9142-251bdd5925b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toAccountId</value>
      <webElementGuid>662064dc-1248-462b-9a73-835befab765e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>4c9cbcf9-328f-4b40-a4fd-02361f861dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>accounts.toAccountId</value>
      <webElementGuid>e8b4e49a-e532-4f92-ae5b-81816250cdd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>account.id for account in accounts track by account.id</value>
      <webElementGuid>bd99d128-277e-4eff-92f7-33286aa4dfeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1623016563166741678517007</value>
      <webElementGuid>567701f1-12d3-4096-97ab-5fb8c760593a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toAccountId&quot;)</value>
      <webElementGuid>029e8463-78ad-4280-a6be-012d6743362f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='toAccountId']</value>
      <webElementGuid>6295b43e-1cfe-415e-a6bc-7a0207069b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/div/select[2]</value>
      <webElementGuid>573e163b-2576-4125-96ca-b19f5c5654f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount:'])[1]/following::select[2]</value>
      <webElementGuid>9f863900-36e7-4618-9da6-5ea771dcf016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::select[1]</value>
      <webElementGuid>de314420-5fbf-44b8-9657-745c2900c20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>f1e6681b-2c6e-45c8-82da-7c84c34c8af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'toAccountId' and (text() = '1623016563166741678517007' or . = '1623016563166741678517007')]</value>
      <webElementGuid>558824ff-3970-4781-88cf-dab67099634c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
