<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select to account</name>
   <tag></tag>
   <elementGuidId>0863a5a4-2dd5-4f3c-8117-8df1efb41ea8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toAccountId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='toAccountId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>28e09f45-d7c9-4ca0-a1c5-ad4268ea12c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toAccountId</value>
      <webElementGuid>e9201bd2-ea1b-4cbe-97c3-a72fcfd95202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>5419b5f5-6202-4f53-8336-1f0313e4613f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>accounts.toAccountId</value>
      <webElementGuid>cc0f7f62-54a5-4ecf-9a0a-8c204e421da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>account.id for account in accounts track by account.id</value>
      <webElementGuid>2ba415fe-d24e-4a70-b083-1c49c12e5b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1623016563166741678517007</value>
      <webElementGuid>551b6cd9-9db3-41e4-901a-fddf50f0d029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toAccountId&quot;)</value>
      <webElementGuid>45d6eb21-a5bd-480a-a0ed-2ddbbae4fef7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='toAccountId']</value>
      <webElementGuid>d385d6d8-7998-46dd-9724-18dad46fecb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/div/select[2]</value>
      <webElementGuid>5953012e-4ad7-49cf-b6d3-3480ac3a5cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount:'])[1]/following::select[2]</value>
      <webElementGuid>3049439d-d90a-47da-9154-147b39c8e24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::select[1]</value>
      <webElementGuid>54948ed7-ccd3-4e80-b43f-de35e909a540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>7322d009-8a67-4c36-8277-5c549c35b502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'toAccountId' and (text() = '1623016563166741678517007' or . = '1623016563166741678517007')]</value>
      <webElementGuid>f8b61fa2-1466-401e-862a-13db10d002bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
