<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input Phone</name>
   <tag></tag>
   <elementGuidId>ae38f2ff-85e5-4fa5-9e0f-7f9edb5bede2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer.phoneNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5cc5042b-b37b-4546-817e-091d29915d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer.phoneNumber</value>
      <webElementGuid>ca655e79-57f5-431c-ab6e-2cd3a60a7f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer.phoneNumber</value>
      <webElementGuid>bef61177-b834-4f0c-9baf-1c8b558366a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>1ebce310-20b4-4aff-8a85-5ed8c4dbceb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba06d22b-cfb3-4ef4-a858-aab1a51dd6a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>customer.phoneNumber</value>
      <webElementGuid>379ae104-d126-4479-ac73-d39e9cfa4918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer.phoneNumber&quot;)</value>
      <webElementGuid>93937ab5-71c7-4a4e-b680-e7e8e4277cd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer.phoneNumber']</value>
      <webElementGuid>a23c33f6-97b3-433e-b610-42d19efba5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>5c32bb00-048d-406c-b927-1842557d2433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>24695669-d7ce-4747-8779-8b5e4e8c793c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'customer.phoneNumber' and @name = 'customer.phoneNumber' and @type = 'text']</value>
      <webElementGuid>c506ec9d-d2d1-4478-8b90-c3274c7bfa10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
