<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input Last Name</name>
   <tag></tag>
   <elementGuidId>6a94284e-1cd1-4e2a-8d7d-71f1e21d9c0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer.lastName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4583d8a3-b4fc-4408-b012-cae6b8539445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer.lastName</value>
      <webElementGuid>41457111-d7d9-41e9-b80e-dd7f5a0f012b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer.lastName</value>
      <webElementGuid>9a3eb653-e65e-4d1d-98c5-e96b42275e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>ec09ac66-cfee-4d08-9bab-d73a1bca03dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e719fc32-e6b1-47ff-9f9e-7e69d31cc71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>customer.lastName</value>
      <webElementGuid>466d56a1-ab8e-4b02-a6fa-c6450d391a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer.lastName&quot;)</value>
      <webElementGuid>cbb2c5cb-5292-4fe7-ab47-ca7a6bca6027</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer.lastName']</value>
      <webElementGuid>3ff21766-2ee0-4c3e-862d-60c32bfb5a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>76ec29e4-067e-410c-af92-a7fef997f2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>b2aea148-329b-458f-b7a1-23bb2e421158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'customer.lastName' and @name = 'customer.lastName' and @type = 'text']</value>
      <webElementGuid>e66a43fd-c0f3-4429-832d-c8e6f75f11fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
